name: 'branch cleanup bot'
description: '🧹 Automatically delete merged branches'
author: 'rkneela0912'
inputs:
  github_token:
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'blue'
